# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a3df7cab11300e9ac0cb1d5c206031185d4fa02d629da2f44e4a14e94264e6f9360c75b4c66da737ecdba52c2d6d30f6938e0a782c332ae3b2aaf3f0475206

test:
  secret_key_base: 0dadd6db6a28a940ec2eb7e133665067327d56a5485df307bd15b970ace254055606d48574abf1019f5ff747958e60c138c0733ca20fd7f29b3b76494eea7037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
